/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aman_Blood_bank;

/**
 *
 * @author Aman Kumar Jha
 */
public class prebill extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    String name,blt,s,dt;
    int req,value;
    public prebill(int req,String name,String blt,int value,String dt) {
        this.name=name;
        this.req=req;
        this.blt=blt;
        this.value=value;
        this.dt=dt;
        initComponents();
        nameb.setText(this.name);
        bgb.setText(this.blt);
        nob.setText(Integer.toString(this.req));
        datet.setText(dt);
        
        
    }
    public prebill()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bgb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        goback = new javax.swing.JButton();
        gt = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        datet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(490, 600));
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOOD BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 257, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 98, 148, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BILL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 241, -1));
        getContentPane().add(nameb, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 103, 241, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("COST PER UNIT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 144, -1, -1));

        cpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cprActionPerformed(evt);
            }
        });
        getContentPane().add(cpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 144, 241, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("BLOOD GROUP:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 184, 148, 27));
        getContentPane().add(bgb, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 184, 241, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("NO OF UNITS:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 227, 144, 30));
        getContentPane().add(nob, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 229, 241, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.blue);
        jLabel7.setText("GRAND TOTAL:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 369, -1, 32));

        goback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goback.setText("<<");
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 31));

        gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtActionPerformed(evt);
            }
        });
        getContentPane().add(gt, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 372, 241, 32));

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setText("Total");
        total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalMouseClicked(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 331, 241, 32));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setText("DATE:");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 279, 144, -1));
        getContentPane().add(datet, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 271, 241, 30));

        jLabel8.setText("____________________________________________________________________________");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 460, -1));

        jLabel9.setText("________________________________________________________________________________");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 480, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseClicked
        // TODO add your handling code here:
        
        int pay=0;
        int costper=1500;
        pay=this.req*costper;
        cpr.setText(Integer.toString(costper));
        s= Integer.toString(pay);
        
        gt.setText(s);
        
    }//GEN-LAST:event_totalMouseClicked

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        // TODO add your handling code here:
        frontp bg=new frontp();
        this.setVisible(false);
        bg.setVisible(true);
    }//GEN-LAST:event_gobackMouseClicked

    private void cprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cprActionPerformed

    private void gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new prebill(int,String,String,int).setVisible(true);
                new prebill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bgb;
    private javax.swing.JTextField cpr;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datet;
    private javax.swing.JButton goback;
    private javax.swing.JTextField gt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameb;
    private javax.swing.JTextField nob;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
